- name: Configuring mongodb servers
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mong.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present
  