- name: configuring catalogue module
  hosts: catalogue
  become: yes
  tasks:
  - name: disbale nodejs
    ansible.builtin.command:
      cmd: dnf module disable nodejs -y
  - name: enable nodejs
    ansible.builtin.command:
      cmd: dnf module enable nodejs:20 -y
  - name: configure the application by cretaing system user
    ansible.builtin.user:
      name: roboshop
      system: True
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user
  - name: remove /app directory
    ansible.builtin.file:
      path: /app
      state: absent
  - name: delete catalogue.zip in tmp directory
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent
  - name: crete /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download catalogue.zip file
    ansible.builtin.get_url:
      url: /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  - name: unzip catalogue.zip
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      remote_src: yes
      dest: /app


