- name: configuring catalogue module
  hosts: catalogue
  become: yes
  tasks:
  - name: disbale nodejs
    ansible.builtin.command:
      cmd: dnf module disable nodejs -y
  - name: enable nodejs
    ansible.builtin.command:
      cmd: dnf module enable nodejs:20 -y
  - name: configure the application by cretaing system user
    ansible.builtin.user:
      name: roboshop
      system: True
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user

