[frontend]
;specify all the target servers 
172.31.39.83 ;Course="Ansible" ## indivudual node varaibles
172.31.44.227 ;Course="Terraform"

[catalogue]
172.31.34.249

[cart]
172.31.34.261

[payment]
172.31.34.272


;groups of groups in yaml file near hosts you can mention roboshop then it will fetch all servers
[roboshop:children]
frontend
catalogue
cart
payment

[local]
localhost
;group variables
; [local:vars]
; Course= Ansible
; Trainer= Siva
; Duration= 150 hrs
; ;group variables
; [frontend:vars]
; Course= Ansible
; Trainer= Siva
; Duration= 150 hrs  
